import lockupMarkup from "@/assets/brand/reps-lockup.svg?raw";
import { cn } from "@/lib/utils";

type RepsLockupProps = {
  className?: string;
};

/**
 * REPs footer lockup — "REPs" (Inter ExtraBold, 28pt, 25 tracking) +
 * vertical divider + "The Register of Exercise Professionals" (Inter Regular)
 * — all combined into a single outlined-path SVG.
 *
 * The SVG uses currentColor for fills and the divider stroke, with opacity
 * baked in for the descriptor (0.6) and divider (0.15). Set colour via
 * Tailwind (e.g. text-white); size by setting a height class — width follows
 * the viewBox aspect ratio.
 *
 * Source SVG: src/assets/brand/reps-lockup.svg (generated by /tmp/make_lockup.py).
 */
export function RepsLockup({ className }: RepsLockupProps) {
  return (
    <span
      aria-hidden={false}
      className={cn("inline-block h-7 w-auto select-none [&>svg]:h-full [&>svg]:w-auto", className)}
      dangerouslySetInnerHTML={{ __html: lockupMarkup }}
    />
  );
}
