/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpecialismsRouteImport } from './routes/specialisms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeLegacyRouteImport } from './routes/home-legacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForProfessionalsRouteImport } from './routes/for-professionals'
import { Route as FindAProfessionalRouteImport } from './routes/find-a-professional'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CpdV2RouteImport } from './routes/cpd-v2'
import { Route as CpdLegacyRouteImport } from './routes/cpd-legacy'
import { Route as CpdRouteImport } from './routes/cpd'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparisonMethodologyRouteImport } from './routes/comparison-methodology'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ProfessionsProfessionRouteImport } from './routes/professions.$profession'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as PortalTodayRouteImport } from './routes/portal_.today'
import { Route as PortalProgrammeRouteImport } from './routes/portal_.programme'
import { Route as PortalProfileRouteImport } from './routes/portal_.profile'
import { Route as PortalNutritionRouteImport } from './routes/portal_.nutrition'
import { Route as PortalMessagesRouteImport } from './routes/portal_.messages'
import { Route as PortalCheckInsRouteImport } from './routes/portal_.check-ins'
import { Route as InLocationRouteImport } from './routes/in.$location'
import { Route as FeaturesVisibilityRouteImport } from './routes/features.visibility'
import { Route as FeaturesShopFrontRouteImport } from './routes/features.shop-front'
import { Route as FeaturesOperationsRouteImport } from './routes/features.operations'
import { Route as FeaturesGrowthRouteImport } from './routes/features.growth'
import { Route as FeaturesCoachingRouteImport } from './routes/features.coaching'
import { Route as FeaturesAiRouteImport } from './routes/features.ai'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DevSectionLibraryRouteImport } from './routes/dev.section-library'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard_.settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard_.reviews'
import { Route as DashboardReportsRouteImport } from './routes/dashboard_.reports'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard_.programs'
import { Route as DashboardProfileRouteImport } from './routes/dashboard_.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard_.payments'
import { Route as DashboardNutritionRouteImport } from './routes/dashboard_.nutrition'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard_.messages'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard_.leads'
import { Route as DashboardCpdRouteImport } from './routes/dashboard_.cpd'
import { Route as DashboardContentRouteImport } from './routes/dashboard_.content'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard_.community'
import { Route as DashboardClientsRouteImport } from './routes/dashboard_.clients'
import { Route as DashboardCheckInsRouteImport } from './routes/dashboard_.check-ins'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard_.calendar'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard_.business'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard_.bookings'
import { Route as CompareRepsVsTrainerizeRouteImport } from './routes/compare_.reps-vs-trainerize'
import { Route as CompareRepsVsPtDistinctionRouteImport } from './routes/compare_.reps-vs-pt-distinction'
import { Route as CompareRepsVsMypthubRouteImport } from './routes/compare_.reps-vs-mypthub'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminVerificationRouteImport } from './routes/admin_.verification'
import { Route as AdminSupportRouteImport } from './routes/admin_.support'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin_.reviews'
import { Route as AdminProfessionalsRouteImport } from './routes/admin_.professionals'
import { Route as AdminPaymentsRouteImport } from './routes/admin_.payments'
import { Route as AdminMigrationRouteImport } from './routes/admin_.migration'
import { Route as AdminMembershipsRouteImport } from './routes/admin_.memberships'
import { Route as AdminDirectoryRouteImport } from './routes/admin_.directory'
import { Route as AdminCpdRouteImport } from './routes/admin_.cpd'
import { Route as ProSlugIndexRouteImport } from './routes/pro.$slug.index'
import { Route as ProSlugEnquireRouteImport } from './routes/pro.$slug.enquire'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DashboardClientsSlugRouteImport } from './routes/dashboard_.clients.$slug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialismsRoute = SpecialismsRouteImport.update({
  id: '/specialisms',
  path: '/specialisms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLegacyRoute = HomeLegacyRouteImport.update({
  id: '/home-legacy',
  path: '/home-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProfessionalsRoute = ForProfessionalsRouteImport.update({
  id: '/for-professionals',
  path: '/for-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAProfessionalRoute = FindAProfessionalRouteImport.update({
  id: '/find-a-professional',
  path: '/find-a-professional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdV2Route = CpdV2RouteImport.update({
  id: '/cpd-v2',
  path: '/cpd-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdLegacyRoute = CpdLegacyRouteImport.update({
  id: '/cpd-legacy',
  path: '/cpd-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRoute = CpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonMethodologyRoute = ComparisonMethodologyRouteImport.update({
  id: '/comparison-methodology',
  path: '/comparison-methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionsProfessionRoute = ProfessionsProfessionRouteImport.update({
  id: '/professions/$profession',
  path: '/professions/$profession',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTodayRoute = PortalTodayRouteImport.update({
  id: '/portal_/today',
  path: '/portal/today',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProgrammeRoute = PortalProgrammeRouteImport.update({
  id: '/portal_/programme',
  path: '/portal/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal_/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNutritionRoute = PortalNutritionRouteImport.update({
  id: '/portal_/nutrition',
  path: '/portal/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/portal_/messages',
  path: '/portal/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCheckInsRoute = PortalCheckInsRouteImport.update({
  id: '/portal_/check-ins',
  path: '/portal/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const InLocationRoute = InLocationRouteImport.update({
  id: '/in/$location',
  path: '/in/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesVisibilityRoute = FeaturesVisibilityRouteImport.update({
  id: '/features/visibility',
  path: '/features/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesShopFrontRoute = FeaturesShopFrontRouteImport.update({
  id: '/features/shop-front',
  path: '/features/shop-front',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesOperationsRoute = FeaturesOperationsRouteImport.update({
  id: '/features/operations',
  path: '/features/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesGrowthRoute = FeaturesGrowthRouteImport.update({
  id: '/features/growth',
  path: '/features/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCoachingRoute = FeaturesCoachingRouteImport.update({
  id: '/features/coaching',
  path: '/features/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAiRoute = FeaturesAiRouteImport.update({
  id: '/features/ai',
  path: '/features/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSectionLibraryRoute = DevSectionLibraryRouteImport.update({
  id: '/dev/section-library',
  path: '/dev/section-library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard_/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard_/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard_/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/dashboard_/programs',
  path: '/dashboard/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard_/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard_/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNutritionRoute = DashboardNutritionRouteImport.update({
  id: '/dashboard_/nutrition',
  path: '/dashboard/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard_/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/dashboard_/leads',
  path: '/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCpdRoute = DashboardCpdRouteImport.update({
  id: '/dashboard_/cpd',
  path: '/dashboard/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/dashboard_/content',
  path: '/dashboard/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/dashboard_/community',
  path: '/dashboard/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/dashboard_/clients',
  path: '/dashboard/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCheckInsRoute = DashboardCheckInsRouteImport.update({
  id: '/dashboard_/check-ins',
  path: '/dashboard/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/dashboard_/calendar',
  path: '/dashboard/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/dashboard_/business',
  path: '/dashboard/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard_/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRepsVsTrainerizeRoute = CompareRepsVsTrainerizeRouteImport.update({
  id: '/compare_/reps-vs-trainerize',
  path: '/compare/reps-vs-trainerize',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRepsVsPtDistinctionRoute =
  CompareRepsVsPtDistinctionRouteImport.update({
    id: '/compare_/reps-vs-pt-distinction',
    path: '/compare/reps-vs-pt-distinction',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareRepsVsMypthubRoute = CompareRepsVsMypthubRouteImport.update({
  id: '/compare_/reps-vs-mypthub',
  path: '/compare/reps-vs-mypthub',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin_/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin_/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin_/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfessionalsRoute = AdminProfessionalsRouteImport.update({
  id: '/admin_/professionals',
  path: '/admin/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin_/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/admin_/migration',
  path: '/admin/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/admin_/memberships',
  path: '/admin/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/admin_/directory',
  path: '/admin/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCpdRoute = AdminCpdRouteImport.update({
  id: '/admin_/cpd',
  path: '/admin/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugIndexRoute = ProSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProSlugRoute,
} as any)
const ProSlugEnquireRoute = ProSlugEnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => ProSlugRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/comparison-methodology': typeof ComparisonMethodologyRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/cpd': typeof CpdRoute
  '/cpd-legacy': typeof CpdLegacyRoute
  '/cpd-v2': typeof CpdV2Route
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-legacy': typeof HomeLegacyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisms': typeof SpecialismsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/cpd': typeof AdminCpdRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/c/$slug': typeof CSlugRoute
  '/compare/reps-vs-mypthub': typeof CompareRepsVsMypthubRoute
  '/compare/reps-vs-pt-distinction': typeof CompareRepsVsPtDistinctionRoute
  '/compare/reps-vs-trainerize': typeof CompareRepsVsTrainerizeRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/check-ins': typeof DashboardCheckInsRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/cpd': typeof DashboardCpdRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/nutrition': typeof DashboardNutritionRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dev/section-library': typeof DevSectionLibraryRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/features/ai': typeof FeaturesAiRoute
  '/features/coaching': typeof FeaturesCoachingRoute
  '/features/growth': typeof FeaturesGrowthRoute
  '/features/operations': typeof FeaturesOperationsRoute
  '/features/shop-front': typeof FeaturesShopFrontRoute
  '/features/visibility': typeof FeaturesVisibilityRoute
  '/in/$location': typeof InLocationRoute
  '/portal/check-ins': typeof PortalCheckInsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/nutrition': typeof PortalNutritionRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/programme': typeof PortalProgrammeRoute
  '/portal/today': typeof PortalTodayRoute
  '/pro/$slug': typeof ProSlugRouteWithChildren
  '/professions/$profession': typeof ProfessionsProfessionRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/$slug/enquire': typeof ProSlugEnquireRoute
  '/pro/$slug/': typeof ProSlugIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/comparison-methodology': typeof ComparisonMethodologyRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/cpd': typeof CpdRoute
  '/cpd-legacy': typeof CpdLegacyRoute
  '/cpd-v2': typeof CpdV2Route
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-legacy': typeof HomeLegacyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisms': typeof SpecialismsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/cpd': typeof AdminCpdRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/c/$slug': typeof CSlugRoute
  '/compare/reps-vs-mypthub': typeof CompareRepsVsMypthubRoute
  '/compare/reps-vs-pt-distinction': typeof CompareRepsVsPtDistinctionRoute
  '/compare/reps-vs-trainerize': typeof CompareRepsVsTrainerizeRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/check-ins': typeof DashboardCheckInsRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/cpd': typeof DashboardCpdRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/nutrition': typeof DashboardNutritionRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dev/section-library': typeof DevSectionLibraryRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/features/ai': typeof FeaturesAiRoute
  '/features/coaching': typeof FeaturesCoachingRoute
  '/features/growth': typeof FeaturesGrowthRoute
  '/features/operations': typeof FeaturesOperationsRoute
  '/features/shop-front': typeof FeaturesShopFrontRoute
  '/features/visibility': typeof FeaturesVisibilityRoute
  '/in/$location': typeof InLocationRoute
  '/portal/check-ins': typeof PortalCheckInsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/nutrition': typeof PortalNutritionRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/programme': typeof PortalProgrammeRoute
  '/portal/today': typeof PortalTodayRoute
  '/professions/$profession': typeof ProfessionsProfessionRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources': typeof ResourcesIndexRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/$slug/enquire': typeof ProSlugEnquireRoute
  '/pro/$slug': typeof ProSlugIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/comparison-methodology': typeof ComparisonMethodologyRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/cpd': typeof CpdRoute
  '/cpd-legacy': typeof CpdLegacyRoute
  '/cpd-v2': typeof CpdV2Route
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-legacy': typeof HomeLegacyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisms': typeof SpecialismsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin_/cpd': typeof AdminCpdRoute
  '/admin_/directory': typeof AdminDirectoryRoute
  '/admin_/memberships': typeof AdminMembershipsRoute
  '/admin_/migration': typeof AdminMigrationRoute
  '/admin_/payments': typeof AdminPaymentsRoute
  '/admin_/professionals': typeof AdminProfessionalsRoute
  '/admin_/reviews': typeof AdminReviewsRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/admin_/support': typeof AdminSupportRoute
  '/admin_/verification': typeof AdminVerificationRoute
  '/c/$slug': typeof CSlugRoute
  '/compare_/reps-vs-mypthub': typeof CompareRepsVsMypthubRoute
  '/compare_/reps-vs-pt-distinction': typeof CompareRepsVsPtDistinctionRoute
  '/compare_/reps-vs-trainerize': typeof CompareRepsVsTrainerizeRoute
  '/dashboard_/bookings': typeof DashboardBookingsRoute
  '/dashboard_/business': typeof DashboardBusinessRoute
  '/dashboard_/calendar': typeof DashboardCalendarRoute
  '/dashboard_/check-ins': typeof DashboardCheckInsRoute
  '/dashboard_/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard_/community': typeof DashboardCommunityRoute
  '/dashboard_/content': typeof DashboardContentRoute
  '/dashboard_/cpd': typeof DashboardCpdRoute
  '/dashboard_/leads': typeof DashboardLeadsRoute
  '/dashboard_/messages': typeof DashboardMessagesRoute
  '/dashboard_/nutrition': typeof DashboardNutritionRoute
  '/dashboard_/payments': typeof DashboardPaymentsRoute
  '/dashboard_/profile': typeof DashboardProfileRoute
  '/dashboard_/programs': typeof DashboardProgramsRoute
  '/dashboard_/reports': typeof DashboardReportsRoute
  '/dashboard_/reviews': typeof DashboardReviewsRoute
  '/dashboard_/settings': typeof DashboardSettingsRoute
  '/dev/section-library': typeof DevSectionLibraryRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/features/ai': typeof FeaturesAiRoute
  '/features/coaching': typeof FeaturesCoachingRoute
  '/features/growth': typeof FeaturesGrowthRoute
  '/features/operations': typeof FeaturesOperationsRoute
  '/features/shop-front': typeof FeaturesShopFrontRoute
  '/features/visibility': typeof FeaturesVisibilityRoute
  '/in/$location': typeof InLocationRoute
  '/portal_/check-ins': typeof PortalCheckInsRoute
  '/portal_/messages': typeof PortalMessagesRoute
  '/portal_/nutrition': typeof PortalNutritionRoute
  '/portal_/profile': typeof PortalProfileRoute
  '/portal_/programme': typeof PortalProgrammeRoute
  '/portal_/today': typeof PortalTodayRoute
  '/pro/$slug': typeof ProSlugRouteWithChildren
  '/professions/$profession': typeof ProfessionsProfessionRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/dashboard_/clients/$slug': typeof DashboardClientsSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/$slug/enquire': typeof ProSlugEnquireRoute
  '/pro/$slug/': typeof ProSlugIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/comparison-methodology'
    | '/contact'
    | '/cookies'
    | '/cpd'
    | '/cpd-legacy'
    | '/cpd-v2'
    | '/dashboard'
    | '/find-a-professional'
    | '/for-professionals'
    | '/forgot-password'
    | '/home-legacy'
    | '/how-it-works'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/sitemap.xml'
    | '/specialisms'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin/cpd'
    | '/admin/directory'
    | '/admin/memberships'
    | '/admin/migration'
    | '/admin/payments'
    | '/admin/professionals'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/verification'
    | '/c/$slug'
    | '/compare/reps-vs-mypthub'
    | '/compare/reps-vs-pt-distinction'
    | '/compare/reps-vs-trainerize'
    | '/dashboard/bookings'
    | '/dashboard/business'
    | '/dashboard/calendar'
    | '/dashboard/check-ins'
    | '/dashboard/clients'
    | '/dashboard/community'
    | '/dashboard/content'
    | '/dashboard/cpd'
    | '/dashboard/leads'
    | '/dashboard/messages'
    | '/dashboard/nutrition'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/programs'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dev/section-library'
    | '/email/unsubscribe'
    | '/features/$slug'
    | '/features/ai'
    | '/features/coaching'
    | '/features/growth'
    | '/features/operations'
    | '/features/shop-front'
    | '/features/visibility'
    | '/in/$location'
    | '/portal/check-ins'
    | '/portal/messages'
    | '/portal/nutrition'
    | '/portal/profile'
    | '/portal/programme'
    | '/portal/today'
    | '/pro/$slug'
    | '/professions/$profession'
    | '/resources/$slug'
    | '/resources/'
    | '/dashboard/clients/$slug'
    | '/lovable/email/suppression'
    | '/pro/$slug/enquire'
    | '/pro/$slug/'
    | '/api/public/stripe/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/comparison-methodology'
    | '/contact'
    | '/cookies'
    | '/cpd'
    | '/cpd-legacy'
    | '/cpd-v2'
    | '/dashboard'
    | '/find-a-professional'
    | '/for-professionals'
    | '/forgot-password'
    | '/home-legacy'
    | '/how-it-works'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/sitemap.xml'
    | '/specialisms'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin/cpd'
    | '/admin/directory'
    | '/admin/memberships'
    | '/admin/migration'
    | '/admin/payments'
    | '/admin/professionals'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/verification'
    | '/c/$slug'
    | '/compare/reps-vs-mypthub'
    | '/compare/reps-vs-pt-distinction'
    | '/compare/reps-vs-trainerize'
    | '/dashboard/bookings'
    | '/dashboard/business'
    | '/dashboard/calendar'
    | '/dashboard/check-ins'
    | '/dashboard/clients'
    | '/dashboard/community'
    | '/dashboard/content'
    | '/dashboard/cpd'
    | '/dashboard/leads'
    | '/dashboard/messages'
    | '/dashboard/nutrition'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/programs'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dev/section-library'
    | '/email/unsubscribe'
    | '/features/$slug'
    | '/features/ai'
    | '/features/coaching'
    | '/features/growth'
    | '/features/operations'
    | '/features/shop-front'
    | '/features/visibility'
    | '/in/$location'
    | '/portal/check-ins'
    | '/portal/messages'
    | '/portal/nutrition'
    | '/portal/profile'
    | '/portal/programme'
    | '/portal/today'
    | '/professions/$profession'
    | '/resources/$slug'
    | '/resources'
    | '/dashboard/clients/$slug'
    | '/lovable/email/suppression'
    | '/pro/$slug/enquire'
    | '/pro/$slug'
    | '/api/public/stripe/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/compare'
    | '/comparison-methodology'
    | '/contact'
    | '/cookies'
    | '/cpd'
    | '/cpd-legacy'
    | '/cpd-v2'
    | '/dashboard'
    | '/find-a-professional'
    | '/for-professionals'
    | '/forgot-password'
    | '/home-legacy'
    | '/how-it-works'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/sitemap.xml'
    | '/specialisms'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin_/cpd'
    | '/admin_/directory'
    | '/admin_/memberships'
    | '/admin_/migration'
    | '/admin_/payments'
    | '/admin_/professionals'
    | '/admin_/reviews'
    | '/admin_/settings'
    | '/admin_/support'
    | '/admin_/verification'
    | '/c/$slug'
    | '/compare_/reps-vs-mypthub'
    | '/compare_/reps-vs-pt-distinction'
    | '/compare_/reps-vs-trainerize'
    | '/dashboard_/bookings'
    | '/dashboard_/business'
    | '/dashboard_/calendar'
    | '/dashboard_/check-ins'
    | '/dashboard_/clients'
    | '/dashboard_/community'
    | '/dashboard_/content'
    | '/dashboard_/cpd'
    | '/dashboard_/leads'
    | '/dashboard_/messages'
    | '/dashboard_/nutrition'
    | '/dashboard_/payments'
    | '/dashboard_/profile'
    | '/dashboard_/programs'
    | '/dashboard_/reports'
    | '/dashboard_/reviews'
    | '/dashboard_/settings'
    | '/dev/section-library'
    | '/email/unsubscribe'
    | '/features/$slug'
    | '/features/ai'
    | '/features/coaching'
    | '/features/growth'
    | '/features/operations'
    | '/features/shop-front'
    | '/features/visibility'
    | '/in/$location'
    | '/portal_/check-ins'
    | '/portal_/messages'
    | '/portal_/nutrition'
    | '/portal_/profile'
    | '/portal_/programme'
    | '/portal_/today'
    | '/pro/$slug'
    | '/professions/$profession'
    | '/resources/$slug'
    | '/resources/'
    | '/dashboard_/clients/$slug'
    | '/lovable/email/suppression'
    | '/pro/$slug/enquire'
    | '/pro/$slug/'
    | '/api/public/stripe/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ComparisonMethodologyRoute: typeof ComparisonMethodologyRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CpdRoute: typeof CpdRoute
  CpdLegacyRoute: typeof CpdLegacyRoute
  CpdV2Route: typeof CpdV2Route
  DashboardRoute: typeof DashboardRoute
  FindAProfessionalRoute: typeof FindAProfessionalRoute
  ForProfessionalsRoute: typeof ForProfessionalsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeLegacyRoute: typeof HomeLegacyRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialismsRoute: typeof SpecialismsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminCpdRoute: typeof AdminCpdRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfessionalsRoute: typeof AdminProfessionalsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  CSlugRoute: typeof CSlugRoute
  CompareRepsVsMypthubRoute: typeof CompareRepsVsMypthubRoute
  CompareRepsVsPtDistinctionRoute: typeof CompareRepsVsPtDistinctionRoute
  CompareRepsVsTrainerizeRoute: typeof CompareRepsVsTrainerizeRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCheckInsRoute: typeof DashboardCheckInsRoute
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardCpdRoute: typeof DashboardCpdRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNutritionRoute: typeof DashboardNutritionRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgramsRoute: typeof DashboardProgramsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DevSectionLibraryRoute: typeof DevSectionLibraryRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  FeaturesAiRoute: typeof FeaturesAiRoute
  FeaturesCoachingRoute: typeof FeaturesCoachingRoute
  FeaturesGrowthRoute: typeof FeaturesGrowthRoute
  FeaturesOperationsRoute: typeof FeaturesOperationsRoute
  FeaturesShopFrontRoute: typeof FeaturesShopFrontRoute
  FeaturesVisibilityRoute: typeof FeaturesVisibilityRoute
  InLocationRoute: typeof InLocationRoute
  PortalCheckInsRoute: typeof PortalCheckInsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalNutritionRoute: typeof PortalNutritionRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProgrammeRoute: typeof PortalProgrammeRoute
  PortalTodayRoute: typeof PortalTodayRoute
  ProSlugRoute: typeof ProSlugRouteWithChildren
  ProfessionsProfessionRoute: typeof ProfessionsProfessionRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialisms': {
      id: '/specialisms'
      path: '/specialisms'
      fullPath: '/specialisms'
      preLoaderRoute: typeof SpecialismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-legacy': {
      id: '/home-legacy'
      path: '/home-legacy'
      fullPath: '/home-legacy'
      preLoaderRoute: typeof HomeLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-professionals': {
      id: '/for-professionals'
      path: '/for-professionals'
      fullPath: '/for-professionals'
      preLoaderRoute: typeof ForProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-professional': {
      id: '/find-a-professional'
      path: '/find-a-professional'
      fullPath: '/find-a-professional'
      preLoaderRoute: typeof FindAProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd-v2': {
      id: '/cpd-v2'
      path: '/cpd-v2'
      fullPath: '/cpd-v2'
      preLoaderRoute: typeof CpdV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd-legacy': {
      id: '/cpd-legacy'
      path: '/cpd-legacy'
      fullPath: '/cpd-legacy'
      preLoaderRoute: typeof CpdLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd': {
      id: '/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof CpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison-methodology': {
      id: '/comparison-methodology'
      path: '/comparison-methodology'
      fullPath: '/comparison-methodology'
      preLoaderRoute: typeof ComparisonMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professions/$profession': {
      id: '/professions/$profession'
      path: '/professions/$profession'
      fullPath: '/professions/$profession'
      preLoaderRoute: typeof ProfessionsProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/today': {
      id: '/portal_/today'
      path: '/portal/today'
      fullPath: '/portal/today'
      preLoaderRoute: typeof PortalTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/programme': {
      id: '/portal_/programme'
      path: '/portal/programme'
      fullPath: '/portal/programme'
      preLoaderRoute: typeof PortalProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/profile': {
      id: '/portal_/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/nutrition': {
      id: '/portal_/nutrition'
      path: '/portal/nutrition'
      fullPath: '/portal/nutrition'
      preLoaderRoute: typeof PortalNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/messages': {
      id: '/portal_/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/check-ins': {
      id: '/portal_/check-ins'
      path: '/portal/check-ins'
      fullPath: '/portal/check-ins'
      preLoaderRoute: typeof PortalCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in/$location': {
      id: '/in/$location'
      path: '/in/$location'
      fullPath: '/in/$location'
      preLoaderRoute: typeof InLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/visibility': {
      id: '/features/visibility'
      path: '/features/visibility'
      fullPath: '/features/visibility'
      preLoaderRoute: typeof FeaturesVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/shop-front': {
      id: '/features/shop-front'
      path: '/features/shop-front'
      fullPath: '/features/shop-front'
      preLoaderRoute: typeof FeaturesShopFrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/operations': {
      id: '/features/operations'
      path: '/features/operations'
      fullPath: '/features/operations'
      preLoaderRoute: typeof FeaturesOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/growth': {
      id: '/features/growth'
      path: '/features/growth'
      fullPath: '/features/growth'
      preLoaderRoute: typeof FeaturesGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/coaching': {
      id: '/features/coaching'
      path: '/features/coaching'
      fullPath: '/features/coaching'
      preLoaderRoute: typeof FeaturesCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/ai': {
      id: '/features/ai'
      path: '/features/ai'
      fullPath: '/features/ai'
      preLoaderRoute: typeof FeaturesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/section-library': {
      id: '/dev/section-library'
      path: '/dev/section-library'
      fullPath: '/dev/section-library'
      preLoaderRoute: typeof DevSectionLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/settings': {
      id: '/dashboard_/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/reviews': {
      id: '/dashboard_/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/reports': {
      id: '/dashboard_/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/programs': {
      id: '/dashboard_/programs'
      path: '/dashboard/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/profile': {
      id: '/dashboard_/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/payments': {
      id: '/dashboard_/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/nutrition': {
      id: '/dashboard_/nutrition'
      path: '/dashboard/nutrition'
      fullPath: '/dashboard/nutrition'
      preLoaderRoute: typeof DashboardNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/messages': {
      id: '/dashboard_/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/leads': {
      id: '/dashboard_/leads'
      path: '/dashboard/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/cpd': {
      id: '/dashboard_/cpd'
      path: '/dashboard/cpd'
      fullPath: '/dashboard/cpd'
      preLoaderRoute: typeof DashboardCpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/content': {
      id: '/dashboard_/content'
      path: '/dashboard/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/community': {
      id: '/dashboard_/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/clients': {
      id: '/dashboard_/clients'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/check-ins': {
      id: '/dashboard_/check-ins'
      path: '/dashboard/check-ins'
      fullPath: '/dashboard/check-ins'
      preLoaderRoute: typeof DashboardCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/calendar': {
      id: '/dashboard_/calendar'
      path: '/dashboard/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/business': {
      id: '/dashboard_/business'
      path: '/dashboard/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/bookings': {
      id: '/dashboard_/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/reps-vs-trainerize': {
      id: '/compare_/reps-vs-trainerize'
      path: '/compare/reps-vs-trainerize'
      fullPath: '/compare/reps-vs-trainerize'
      preLoaderRoute: typeof CompareRepsVsTrainerizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/reps-vs-pt-distinction': {
      id: '/compare_/reps-vs-pt-distinction'
      path: '/compare/reps-vs-pt-distinction'
      fullPath: '/compare/reps-vs-pt-distinction'
      preLoaderRoute: typeof CompareRepsVsPtDistinctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/reps-vs-mypthub': {
      id: '/compare_/reps-vs-mypthub'
      path: '/compare/reps-vs-mypthub'
      fullPath: '/compare/reps-vs-mypthub'
      preLoaderRoute: typeof CompareRepsVsMypthubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/verification': {
      id: '/admin_/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/support': {
      id: '/admin_/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reviews': {
      id: '/admin_/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/professionals': {
      id: '/admin_/professionals'
      path: '/admin/professionals'
      fullPath: '/admin/professionals'
      preLoaderRoute: typeof AdminProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/payments': {
      id: '/admin_/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/migration': {
      id: '/admin_/migration'
      path: '/admin/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/memberships': {
      id: '/admin_/memberships'
      path: '/admin/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/directory': {
      id: '/admin_/directory'
      path: '/admin/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cpd': {
      id: '/admin_/cpd'
      path: '/admin/cpd'
      fullPath: '/admin/cpd'
      preLoaderRoute: typeof AdminCpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug/': {
      id: '/pro/$slug/'
      path: '/'
      fullPath: '/pro/$slug/'
      preLoaderRoute: typeof ProSlugIndexRouteImport
      parentRoute: typeof ProSlugRoute
    }
    '/pro/$slug/enquire': {
      id: '/pro/$slug/enquire'
      path: '/enquire'
      fullPath: '/pro/$slug/enquire'
      preLoaderRoute: typeof ProSlugEnquireRouteImport
      parentRoute: typeof ProSlugRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/clients/$slug': {
      id: '/dashboard_/clients/$slug'
      path: '/$slug'
      fullPath: '/dashboard/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardClientsRouteChildren {
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface ProSlugRouteChildren {
  ProSlugEnquireRoute: typeof ProSlugEnquireRoute
  ProSlugIndexRoute: typeof ProSlugIndexRoute
}

const ProSlugRouteChildren: ProSlugRouteChildren = {
  ProSlugEnquireRoute: ProSlugEnquireRoute,
  ProSlugIndexRoute: ProSlugIndexRoute,
}

const ProSlugRouteWithChildren =
  ProSlugRoute._addFileChildren(ProSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ComparisonMethodologyRoute: ComparisonMethodologyRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CpdRoute: CpdRoute,
  CpdLegacyRoute: CpdLegacyRoute,
  CpdV2Route: CpdV2Route,
  DashboardRoute: DashboardRoute,
  FindAProfessionalRoute: FindAProfessionalRoute,
  ForProfessionalsRoute: ForProfessionalsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeLegacyRoute: HomeLegacyRoute,
  HowItWorksRoute: HowItWorksRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialismsRoute: SpecialismsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminCpdRoute: AdminCpdRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfessionalsRoute: AdminProfessionalsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  CSlugRoute: CSlugRoute,
  CompareRepsVsMypthubRoute: CompareRepsVsMypthubRoute,
  CompareRepsVsPtDistinctionRoute: CompareRepsVsPtDistinctionRoute,
  CompareRepsVsTrainerizeRoute: CompareRepsVsTrainerizeRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCheckInsRoute: DashboardCheckInsRoute,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardCpdRoute: DashboardCpdRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNutritionRoute: DashboardNutritionRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgramsRoute: DashboardProgramsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DevSectionLibraryRoute: DevSectionLibraryRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  FeaturesAiRoute: FeaturesAiRoute,
  FeaturesCoachingRoute: FeaturesCoachingRoute,
  FeaturesGrowthRoute: FeaturesGrowthRoute,
  FeaturesOperationsRoute: FeaturesOperationsRoute,
  FeaturesShopFrontRoute: FeaturesShopFrontRoute,
  FeaturesVisibilityRoute: FeaturesVisibilityRoute,
  InLocationRoute: InLocationRoute,
  PortalCheckInsRoute: PortalCheckInsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalNutritionRoute: PortalNutritionRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalProgrammeRoute: PortalProgrammeRoute,
  PortalTodayRoute: PortalTodayRoute,
  ProSlugRoute: ProSlugRouteWithChildren,
  ProfessionsProfessionRoute: ProfessionsProfessionRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
