/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindAProfessionalRouteImport } from './routes/find-a-professional'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAProfessionalRoute = FindAProfessionalRouteImport.update({
  id: '/find-a-professional',
  path: '/find-a-professional',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/pro/$slug': typeof ProSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/pro/$slug': typeof ProSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/pro/$slug': typeof ProSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-a-professional' | '/login' | '/signup' | '/pro/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-a-professional' | '/login' | '/signup' | '/pro/$slug'
  id:
    | '__root__'
    | '/'
    | '/find-a-professional'
    | '/login'
    | '/signup'
    | '/pro/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindAProfessionalRoute: typeof FindAProfessionalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProSlugRoute: typeof ProSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-professional': {
      id: '/find-a-professional'
      path: '/find-a-professional'
      fullPath: '/find-a-professional'
      preLoaderRoute: typeof FindAProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindAProfessionalRoute: FindAProfessionalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProSlugRoute: ProSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
