/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindAProfessionalRouteImport } from './routes/find-a-professional'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard_.programs'
import { Route as DashboardProfileRouteImport } from './routes/dashboard_.profile'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard_.leads'
import { Route as DashboardCheckInsRouteImport } from './routes/dashboard_.check-ins'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard_.calendar'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard_.bookings'
import { Route as DashboardClientsSlugRouteImport } from './routes/dashboard_.clients.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAProfessionalRoute = FindAProfessionalRouteImport.update({
  id: '/find-a-professional',
  path: '/find-a-professional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/dashboard_/programs',
  path: '/dashboard/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard_/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/dashboard_/leads',
  path: '/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCheckInsRoute = DashboardCheckInsRouteImport.update({
  id: '/dashboard_/check-ins',
  path: '/dashboard/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/dashboard_/calendar',
  path: '/dashboard/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard_/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/dashboard_/clients/$slug',
  path: '/dashboard/clients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/check-ins': typeof DashboardCheckInsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/pro/$slug': typeof ProSlugRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/check-ins': typeof DashboardCheckInsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/pro/$slug': typeof ProSlugRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/find-a-professional': typeof FindAProfessionalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard_/bookings': typeof DashboardBookingsRoute
  '/dashboard_/calendar': typeof DashboardCalendarRoute
  '/dashboard_/check-ins': typeof DashboardCheckInsRoute
  '/dashboard_/leads': typeof DashboardLeadsRoute
  '/dashboard_/profile': typeof DashboardProfileRoute
  '/dashboard_/programs': typeof DashboardProgramsRoute
  '/pro/$slug': typeof ProSlugRoute
  '/dashboard_/clients/$slug': typeof DashboardClientsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/find-a-professional'
    | '/login'
    | '/signup'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/check-ins'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/programs'
    | '/pro/$slug'
    | '/dashboard/clients/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/find-a-professional'
    | '/login'
    | '/signup'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/check-ins'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/programs'
    | '/pro/$slug'
    | '/dashboard/clients/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/find-a-professional'
    | '/login'
    | '/signup'
    | '/dashboard_/bookings'
    | '/dashboard_/calendar'
    | '/dashboard_/check-ins'
    | '/dashboard_/leads'
    | '/dashboard_/profile'
    | '/dashboard_/programs'
    | '/pro/$slug'
    | '/dashboard_/clients/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  FindAProfessionalRoute: typeof FindAProfessionalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCheckInsRoute: typeof DashboardCheckInsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgramsRoute: typeof DashboardProgramsRoute
  ProSlugRoute: typeof ProSlugRoute
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-professional': {
      id: '/find-a-professional'
      path: '/find-a-professional'
      fullPath: '/find-a-professional'
      preLoaderRoute: typeof FindAProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/programs': {
      id: '/dashboard_/programs'
      path: '/dashboard/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/profile': {
      id: '/dashboard_/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/leads': {
      id: '/dashboard_/leads'
      path: '/dashboard/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/check-ins': {
      id: '/dashboard_/check-ins'
      path: '/dashboard/check-ins'
      fullPath: '/dashboard/check-ins'
      preLoaderRoute: typeof DashboardCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/calendar': {
      id: '/dashboard_/calendar'
      path: '/dashboard/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/bookings': {
      id: '/dashboard_/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/clients/$slug': {
      id: '/dashboard_/clients/$slug'
      path: '/dashboard/clients/$slug'
      fullPath: '/dashboard/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  FindAProfessionalRoute: FindAProfessionalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCheckInsRoute: DashboardCheckInsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgramsRoute: DashboardProgramsRoute,
  ProSlugRoute: ProSlugRoute,
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
